const actionTypes = {
  SAMPLE_ACTION: 'SAMPLE_ACTION',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILED: 'AUTH_FAILED',
  MENU_FETCH_SUCCESS: 'MENU_FETCH_SUCCESS',
  MENU_ERROR: 'MENU_ERROR',
  MENU_POST_SUCCESS: 'MENU_POST_SUCCESS',
  MENU_DELETE_SUCCESS: 'MENU_DELETE_SUCCESS',
  ADD_TO_ORDER: 'ADD_TO_ORDER',
  REMOVE_FROM_ORDER: 'REMOVE_FROM _ORDER',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
};

export default actionTypes;
